//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:43:54 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// out                            O    17
// RDY_out                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// out_rd_add                     I    17
// out_wr_add                     I    17
// out_wea                        I     1
//
// Combinational paths from inputs to outputs:
//   (out_rd_add, out_wr_add, out_wea) -> out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkAddressMux(CLK,
		    RST_N,

		    out_rd_add,
		    out_wr_add,
		    out_wea,
		    out,
		    RDY_out);
  input  CLK;
  input  RST_N;

  // value method out
  input  [16 : 0] out_rd_add;
  input  [16 : 0] out_wr_add;
  input  out_wea;
  output [16 : 0] out;
  output RDY_out;

  // signals for module outputs
  wire [16 : 0] out;
  wire RDY_out;

  // value method out
  assign out = out_wea ? out_wr_add : out_rd_add ;
  assign RDY_out = 1'd1 ;
endmodule  // mkAddressMux

