//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:44:26 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// camera_reset                   O     1
// RDY_camera_reset               O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// camera_reset_crst              I     1
//
// Combinational paths from inputs to outputs:
//   camera_reset_crst -> camera_reset
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCameraResetClk(CLK,
			RST_N,

			camera_reset_crst,
			camera_reset,
			RDY_camera_reset);
  input  CLK;
  input  RST_N;

  // value method camera_reset
  input  camera_reset_crst;
  output camera_reset;
  output RDY_camera_reset;

  // signals for module outputs
  wire RDY_camera_reset, camera_reset;

  // value method camera_reset
  assign camera_reset = ~camera_reset_crst ;
  assign RDY_camera_reset = 1'd1 ;
endmodule  // mkCameraResetClk

