//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:44:47 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// vsync_detected                 O     1 reg
// RDY_vsync_detected             O     1 const
// capture_reset_out              O     1 reg
// RDY_capture_reset_out          O     1 const
// vsync                          I     1
// reset                          I     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCaptureStarter(vsync,
			reset,
			CLK,
			RST_N,

			vsync_detected,
			RDY_vsync_detected,

			capture_reset_out,
			RDY_capture_reset_out);
  input  vsync;
  input  reset;
  input  CLK;
  input  RST_N;

  // value method vsync_detected
  output vsync_detected;
  output RDY_vsync_detected;

  // value method capture_reset_out
  output capture_reset_out;
  output RDY_capture_reset_out;

  // signals for module outputs
  wire RDY_capture_reset_out,
       RDY_vsync_detected,
       capture_reset_out,
       vsync_detected;

  // register c_reset
  reg c_reset;
  wire c_reset$D_IN, c_reset$EN;

  // register detected
  reg detected;
  wire detected$D_IN, detected$EN;

  // value method vsync_detected
  assign vsync_detected = detected ;
  assign RDY_vsync_detected = 1'd1 ;

  // value method capture_reset_out
  assign capture_reset_out = c_reset ;
  assign RDY_capture_reset_out = 1'd1 ;

  // register c_reset
  assign c_reset$D_IN = reset ;
  assign c_reset$EN = vsync ;

  // register detected
  assign detected$D_IN = !reset ;
  assign detected$EN = vsync ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        c_reset <= `BSV_ASSIGNMENT_DELAY 1'd0;
	detected <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (c_reset$EN) c_reset <= `BSV_ASSIGNMENT_DELAY c_reset$D_IN;
	if (detected$EN) detected <= `BSV_ASSIGNMENT_DELAY detected$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    c_reset = 1'h0;
    detected = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCaptureStarter

