//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:47:18 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// out                            O     8
// RDY_out                        O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// out_select                     I     1
// out_din                        I     8
//
// Combinational paths from inputs to outputs:
//   (out_select, out_din) -> out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkDataMux(CLK,
		 RST_N,

		 out_select,
		 out_din,
		 out,
		 RDY_out);
  input  CLK;
  input  RST_N;

  // value method out
  input  out_select;
  input  [7 : 0] out_din;
  output [7 : 0] out;
  output RDY_out;

  // signals for module outputs
  wire [7 : 0] out;
  wire RDY_out;

  // value method out
  assign out = out_select ? out_din : 8'b0 ;
  assign RDY_out = 1'd1 ;
endmodule  // mkDataMux

