//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:49:16 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_put                        O     1
// read                           O     8
// RDY_read                       O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// put_addr                       I    17 reg
// put_data                       I     8 reg
// put_wea                        I     1
// EN_put                         I     1
// EN_read                        I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFrameBuffer(CLK,
		     RST_N,

		     put_addr,
		     put_data,
		     put_wea,
		     EN_put,
		     RDY_put,

		     EN_read,
		     read,
		     RDY_read);
  input  CLK;
  input  RST_N;

  // action method put
  input  [16 : 0] put_addr;
  input  [7 : 0] put_data;
  input  put_wea;
  input  EN_put;
  output RDY_put;

  // actionvalue method read
  input  EN_read;
  output [7 : 0] read;
  output RDY_read;

  // signals for module outputs
  wire [7 : 0] read;
  wire RDY_put, RDY_read;

  // inlined wires
  wire [1 : 0] mem_serverAdapter_s1_1$wget,
	       mem_serverAdapter_writeWithResp$wget;
  wire mem_serverAdapter_cnt_1$whas, mem_serverAdapter_outData_enqw$whas;

  // register mem_serverAdapter_cnt
  reg [2 : 0] mem_serverAdapter_cnt;
  wire [2 : 0] mem_serverAdapter_cnt$D_IN;
  wire mem_serverAdapter_cnt$EN;

  // register mem_serverAdapter_s1
  reg [1 : 0] mem_serverAdapter_s1;
  wire [1 : 0] mem_serverAdapter_s1$D_IN;
  wire mem_serverAdapter_s1$EN;

  // ports of submodule mem_memory
  wire [16 : 0] mem_memory$ADDR;
  wire [7 : 0] mem_memory$DI, mem_memory$DO;
  wire mem_memory$EN, mem_memory$WE;

  // ports of submodule mem_serverAdapter_outData_beforeDeq
  wire mem_serverAdapter_outData_beforeDeq$D_IN,
       mem_serverAdapter_outData_beforeDeq$EN,
       mem_serverAdapter_outData_beforeDeq$Q_OUT;

  // ports of submodule mem_serverAdapter_outData_beforeEnq
  wire mem_serverAdapter_outData_beforeEnq$D_IN,
       mem_serverAdapter_outData_beforeEnq$EN,
       mem_serverAdapter_outData_beforeEnq$Q_OUT;

  // ports of submodule mem_serverAdapter_outData_ff
  wire [7 : 0] mem_serverAdapter_outData_ff$D_IN,
	       mem_serverAdapter_outData_ff$D_OUT;
  wire mem_serverAdapter_outData_ff$CLR,
       mem_serverAdapter_outData_ff$DEQ,
       mem_serverAdapter_outData_ff$EMPTY_N,
       mem_serverAdapter_outData_ff$ENQ,
       mem_serverAdapter_outData_ff$FULL_N;

  // remaining internal signals
  wire [2 : 0] mem_serverAdapter_cnt_6_PLUS_IF_mem_serverAdap_ETC___d22;

  // action method put
  assign RDY_put = (mem_serverAdapter_cnt ^ 3'h4) < 3'd7 ;

  // actionvalue method read
  assign read =
	     mem_serverAdapter_outData_ff$EMPTY_N ?
	       mem_serverAdapter_outData_ff$D_OUT :
	       mem_memory$DO ;
  assign RDY_read =
	     mem_serverAdapter_outData_beforeDeq$Q_OUT &&
	     (mem_serverAdapter_outData_ff$EMPTY_N ||
	      mem_serverAdapter_outData_enqw$whas) ;

  // submodule mem_memory
  BRAM1 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd17),
	  .DATA_WIDTH(32'd8),
	  .MEMSIZE(18'd76800)) mem_memory(.CLK(CLK),
					  .ADDR(mem_memory$ADDR),
					  .DI(mem_memory$DI),
					  .WE(mem_memory$WE),
					  .EN(mem_memory$EN),
					  .DO(mem_memory$DO));

  // submodule mem_serverAdapter_outData_beforeDeq
  RevertReg #(.width(32'd1),
	      .init(1'd1)) mem_serverAdapter_outData_beforeDeq(.CLK(CLK),
							       .D_IN(mem_serverAdapter_outData_beforeDeq$D_IN),
							       .EN(mem_serverAdapter_outData_beforeDeq$EN),
							       .Q_OUT(mem_serverAdapter_outData_beforeDeq$Q_OUT));

  // submodule mem_serverAdapter_outData_beforeEnq
  RevertReg #(.width(32'd1),
	      .init(1'd1)) mem_serverAdapter_outData_beforeEnq(.CLK(CLK),
							       .D_IN(mem_serverAdapter_outData_beforeEnq$D_IN),
							       .EN(mem_serverAdapter_outData_beforeEnq$EN),
							       .Q_OUT(mem_serverAdapter_outData_beforeEnq$Q_OUT));

  // submodule mem_serverAdapter_outData_ff
  SizedFIFO #(.p1width(32'd8),
	      .p2depth(32'd3),
	      .p3cntr_width(32'd1),
	      .guarded(1'd0)) mem_serverAdapter_outData_ff(.RST(RST_N),
							   .CLK(CLK),
							   .D_IN(mem_serverAdapter_outData_ff$D_IN),
							   .ENQ(mem_serverAdapter_outData_ff$ENQ),
							   .DEQ(mem_serverAdapter_outData_ff$DEQ),
							   .CLR(mem_serverAdapter_outData_ff$CLR),
							   .D_OUT(mem_serverAdapter_outData_ff$D_OUT),
							   .FULL_N(mem_serverAdapter_outData_ff$FULL_N),
							   .EMPTY_N(mem_serverAdapter_outData_ff$EMPTY_N));

  // inlined wires
  assign mem_serverAdapter_outData_enqw$whas =
	     mem_serverAdapter_outData_ff$FULL_N && mem_serverAdapter_s1[1] &&
	     mem_serverAdapter_s1[0] ;
  assign mem_serverAdapter_cnt_1$whas =
	     EN_put &&
	     (!mem_serverAdapter_writeWithResp$wget[1] ||
	      mem_serverAdapter_writeWithResp$wget[0]) ;
  assign mem_serverAdapter_writeWithResp$wget = { put_wea, 1'd0 } ;
  assign mem_serverAdapter_s1_1$wget =
	     { 1'd1,
	       !mem_serverAdapter_writeWithResp$wget[1] ||
	       mem_serverAdapter_writeWithResp$wget[0] } ;

  // register mem_serverAdapter_cnt
  assign mem_serverAdapter_cnt$D_IN =
	     mem_serverAdapter_cnt_6_PLUS_IF_mem_serverAdap_ETC___d22 ;
  assign mem_serverAdapter_cnt$EN = mem_serverAdapter_cnt_1$whas || EN_read ;

  // register mem_serverAdapter_s1
  assign mem_serverAdapter_s1$D_IN =
	     EN_put ? mem_serverAdapter_s1_1$wget : 2'd0 ;
  assign mem_serverAdapter_s1$EN = 1'd1 ;

  // submodule mem_memory
  assign mem_memory$ADDR = put_addr ;
  assign mem_memory$DI = put_data ;
  assign mem_memory$WE = put_wea ;
  assign mem_memory$EN = EN_put ;

  // submodule mem_serverAdapter_outData_beforeDeq
  assign mem_serverAdapter_outData_beforeDeq$D_IN = 1'd1 ;
  assign mem_serverAdapter_outData_beforeDeq$EN = EN_read ;

  // submodule mem_serverAdapter_outData_beforeEnq
  assign mem_serverAdapter_outData_beforeEnq$D_IN = 1'd1 ;
  assign mem_serverAdapter_outData_beforeEnq$EN =
	     mem_serverAdapter_outData_enqw$whas ;

  // submodule mem_serverAdapter_outData_ff
  assign mem_serverAdapter_outData_ff$D_IN = mem_memory$DO ;
  assign mem_serverAdapter_outData_ff$ENQ =
	     mem_serverAdapter_outData_enqw$whas &&
	     (!EN_read || mem_serverAdapter_outData_ff$EMPTY_N) ;
  assign mem_serverAdapter_outData_ff$DEQ =
	     EN_read && mem_serverAdapter_outData_ff$EMPTY_N ;
  assign mem_serverAdapter_outData_ff$CLR = 1'b0 ;

  // remaining internal signals
  assign mem_serverAdapter_cnt_6_PLUS_IF_mem_serverAdap_ETC___d22 =
	     mem_serverAdapter_cnt +
	     (mem_serverAdapter_cnt_1$whas ? 3'd1 : 3'd0) +
	     (EN_read ? 3'd7 : 3'd0) ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        mem_serverAdapter_cnt <= `BSV_ASSIGNMENT_DELAY 3'd0;
	mem_serverAdapter_s1 <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (mem_serverAdapter_cnt$EN)
	  mem_serverAdapter_cnt <= `BSV_ASSIGNMENT_DELAY
	      mem_serverAdapter_cnt$D_IN;
	if (mem_serverAdapter_s1$EN)
	  mem_serverAdapter_s1 <= `BSV_ASSIGNMENT_DELAY
	      mem_serverAdapter_s1$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    mem_serverAdapter_cnt = 3'h2;
    mem_serverAdapter_s1 = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (mem_serverAdapter_s1[1] &&
	  (!mem_serverAdapter_outData_beforeEnq$Q_OUT ||
	   !mem_serverAdapter_outData_beforeDeq$Q_OUT ||
	   !mem_serverAdapter_outData_ff$FULL_N))
	$display("ERROR: %m: mkBRAMAdapter overrun");
  end
  // synopsys translate_on
endmodule  // mkFrameBuffer

