//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:56:48 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// address                        O    17 reg
// RDY_address                    O     1 const
// pix_out                        O     8
// RDY_pix_out                    O     1 const
// data_in                        I     8
// video_on                       I     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkSobelStoch(data_in,
		    video_on,
		    CLK,
		    RST_N,

		    address,
		    RDY_address,

		    pix_out,
		    RDY_pix_out);
  input  [7 : 0] data_in;
  input  video_on;
  input  CLK;
  input  RST_N;

  // value method address
  output [16 : 0] address;
  output RDY_address;

  // value method pix_out
  output [7 : 0] pix_out;
  output RDY_pix_out;

  // signals for module outputs
  wire [16 : 0] address;
  wire [7 : 0] pix_out;
  wire RDY_address, RDY_pix_out;

  // register addr_reg
  reg [16 : 0] addr_reg;
  reg [16 : 0] addr_reg$D_IN;
  wire addr_reg$EN;

  // register col_count
  reg [9 : 0] col_count;
  wire [9 : 0] col_count$D_IN;
  wire col_count$EN;

  // register d_curr
  reg [7 : 0] d_curr;
  wire [7 : 0] d_curr$D_IN;
  wire d_curr$EN;

  // register d_prev
  reg [7 : 0] d_prev;
  wire [7 : 0] d_prev$D_IN;
  wire d_prev$EN;

  // register o_0_0
  reg [7 : 0] o_0_0;
  wire [7 : 0] o_0_0$D_IN;
  wire o_0_0$EN;

  // register o_0_1
  reg [7 : 0] o_0_1;
  wire [7 : 0] o_0_1$D_IN;
  wire o_0_1$EN;

  // register o_0_2
  reg [7 : 0] o_0_2;
  wire [7 : 0] o_0_2$D_IN;
  wire o_0_2$EN;

  // register o_1_0
  reg [7 : 0] o_1_0;
  wire [7 : 0] o_1_0$D_IN;
  wire o_1_0$EN;

  // register o_1_1
  reg [7 : 0] o_1_1;
  wire [7 : 0] o_1_1$D_IN;
  wire o_1_1$EN;

  // register o_1_2
  reg [7 : 0] o_1_2;
  wire [7 : 0] o_1_2$D_IN;
  wire o_1_2$EN;

  // register o_2_0
  reg [7 : 0] o_2_0;
  wire [7 : 0] o_2_0$D_IN;
  wire o_2_0$EN;

  // register o_2_1
  reg [7 : 0] o_2_1;
  wire [7 : 0] o_2_1$D_IN;
  wire o_2_1$EN;

  // register o_2_2
  reg [7 : 0] o_2_2;
  wire [7 : 0] o_2_2$D_IN;
  wire o_2_2$EN;

  // register res_reg
  reg [7 : 0] res_reg;
  wire [7 : 0] res_reg$D_IN;
  wire res_reg$EN;

  // register row_count
  reg [9 : 0] row_count;
  wire [9 : 0] row_count$D_IN;
  wire row_count$EN;

  // register state
  reg [1 : 0] state;
  reg [1 : 0] state$D_IN;
  wire state$EN;

  // remaining internal signals
  wire [33 : 0] _320_MUL_0_CONCAT_0b0_CONCAT_row_count_0_1_PLUS_ETC___d15,
		_320_MUL_0_CONCAT_0b0_CONCAT_row_count_0_1_PLUS_ETC___d26,
		_320_MUL_0_CONCAT_row_count_0_BITS_9_TO_1_8_9___d20;
  wire [16 : 0] x__h1043,
		x__h1161,
		x__h1241,
		x__h1250,
		y__h1094,
		y__h1177,
		y__h1257;
  wire [15 : 0] _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d193;
  wire [10 : 0] x__h1098, x__h1261;
  wire [9 : 0] x__h4972;
  wire [7 : 0] _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d156,
	       _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d165,
	       _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d174,
	       _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d183,
	       _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d192,
	       _theResult_____1__h1512,
	       _theResult_____1__h2041,
	       _theResult_____1__h2569,
	       _theResult_____2__h1511,
	       _theResult_____2__h2040,
	       _theResult_____2__h2568,
	       _theResult_____3__h1510,
	       _theResult_____3__h2039,
	       _theResult_____3__h2567,
	       _theResult_____4__h1509,
	       _theResult_____4__h2038,
	       _theResult_____4__h2566,
	       _theResult_____5__h1508,
	       _theResult_____5__h2037,
	       _theResult_____5__h2565,
	       _theResult_____6__h1507,
	       _theResult_____6__h2036,
	       _theResult_____6__h2564,
	       o_0_0_47_XOR_o_0_2_9___d148,
	       o_0_0_47_XOR_o_2_0_52___d153,
	       o_0_1_8_XOR_o_2_1_06___d143,
	       o_1_0_39_XOR_o_1_2_3___d140,
	       result__h1519,
	       result__h1529,
	       result__h1539,
	       result__h1549,
	       result__h1559,
	       result__h1569,
	       result__h2048,
	       result__h2058,
	       result__h2068,
	       result__h2078,
	       result__h2088,
	       result__h2098,
	       result__h2575,
	       result__h2585,
	       result__h2595,
	       result__h2605,
	       result__h2615,
	       result__h2625;

  // value method address
  assign address = addr_reg ;
  assign RDY_address = 1'd1 ;

  // value method pix_out
  assign pix_out =
	     (row_count != 10'd0 && row_count <= 10'd478) ? res_reg : 8'd0 ;
  assign RDY_pix_out = 1'd1 ;

  // register addr_reg
  always@(state or x__h1241 or x__h1043 or x__h1161)
  begin
    case (state)
      2'd0: addr_reg$D_IN = x__h1043;
      2'd1: addr_reg$D_IN = x__h1161;
      default: addr_reg$D_IN = x__h1241;
    endcase
  end
  assign addr_reg$EN =
	     video_on && (state == 2'd0 || state == 2'd1 || state == 2'd2) ;

  // register col_count
  assign col_count$D_IN = (col_count == 10'd639) ? 10'd0 : x__h4972 ;
  assign col_count$EN = video_on && state == 2'd3 ;

  // register d_curr
  assign d_curr$D_IN = data_in ;
  assign d_curr$EN = video_on && state == 2'd2 ;

  // register d_prev
  assign d_prev$D_IN = data_in ;
  assign d_prev$EN = video_on && state == 2'd1 ;

  // register o_0_0
  assign o_0_0$D_IN = o_0_1 ;
  assign o_0_0$EN = video_on && state == 2'd3 ;

  // register o_0_1
  assign o_0_1$D_IN = o_0_2 ;
  assign o_0_1$EN = video_on && state == 2'd3 ;

  // register o_0_2
  assign o_0_2$D_IN =
	     (d_prev < 8'd224) ? _theResult_____1__h1512 : result__h1519 ;
  assign o_0_2$EN = video_on && state == 2'd3 ;

  // register o_1_0
  assign o_1_0$D_IN = o_1_1 ;
  assign o_1_0$EN = video_on && state == 2'd3 ;

  // register o_1_1
  assign o_1_1$D_IN = o_1_2 ;
  assign o_1_1$EN = video_on && state == 2'd3 ;

  // register o_1_2
  assign o_1_2$D_IN =
	     (d_curr < 8'd224) ? _theResult_____1__h2041 : result__h2048 ;
  assign o_1_2$EN = video_on && state == 2'd3 ;

  // register o_2_0
  assign o_2_0$D_IN = o_2_1 ;
  assign o_2_0$EN = video_on && state == 2'd3 ;

  // register o_2_1
  assign o_2_1$D_IN = o_2_2 ;
  assign o_2_1$EN = video_on && state == 2'd3 ;

  // register o_2_2
  assign o_2_2$D_IN =
	     (data_in < 8'd224) ? _theResult_____1__h2569 : result__h2575 ;
  assign o_2_2$EN = video_on && state == 2'd3 ;

  // register res_reg
  assign res_reg$D_IN =
	     _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d193[7:0] ;
  assign res_reg$EN = video_on && state == 2'd3 ;

  // register row_count
  assign row_count$D_IN = (row_count == 10'd479) ? 10'd0 : row_count + 10'd1 ;
  assign row_count$EN = video_on && state == 2'd3 && col_count == 10'd639 ;

  // register state
  always@(state)
  begin
    case (state)
      2'd0: state$D_IN = 2'd1;
      2'd1: state$D_IN = 2'd2;
      2'd2: state$D_IN = 2'd3;
      2'd3: state$D_IN = 2'd0;
    endcase
  end
  assign state$EN = video_on ;

  // remaining internal signals
  assign _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d156 =
	     { 7'd0, o_1_0_39_XOR_o_1_2_3___d140[0] } +
	     { 7'd0, o_0_1_8_XOR_o_2_1_06___d143[0] } +
	     { 7'd0, o_0_0_47_XOR_o_0_2_9___d148[1] } +
	     { 7'd0, o_0_0_47_XOR_o_2_0_52___d153[1] } ;
  assign _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d165 =
	     _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d156 +
	     { 7'd0, o_1_0_39_XOR_o_1_2_3___d140[2] } +
	     { 7'd0, o_0_1_8_XOR_o_2_1_06___d143[2] } +
	     { 7'd0, o_0_0_47_XOR_o_0_2_9___d148[3] } ;
  assign _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d174 =
	     _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d165 +
	     { 7'd0, o_0_0_47_XOR_o_2_0_52___d153[3] } +
	     { 7'd0, o_1_0_39_XOR_o_1_2_3___d140[4] } +
	     { 7'd0, o_0_1_8_XOR_o_2_1_06___d143[4] } ;
  assign _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d183 =
	     _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d174 +
	     { 7'd0, o_0_0_47_XOR_o_0_2_9___d148[5] } +
	     { 7'd0, o_0_0_47_XOR_o_2_0_52___d153[5] } +
	     { 7'd0, o_1_0_39_XOR_o_1_2_3___d140[6] } ;
  assign _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d192 =
	     _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d183 +
	     { 7'd0, o_0_1_8_XOR_o_2_1_06___d143[6] } +
	     { 7'd0, o_0_0_47_XOR_o_0_2_9___d148[7] } +
	     { 7'd0, o_0_0_47_XOR_o_2_0_52___d153[7] } ;
  assign _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d193 =
	     _0_CONCAT_o_1_0_39_XOR_o_1_2_3_40_BIT_0_41_42_P_ETC___d192 *
	     8'd15 ;
  assign _320_MUL_0_CONCAT_0b0_CONCAT_row_count_0_1_PLUS_ETC___d15 =
	     17'd320 * y__h1094 ;
  assign _320_MUL_0_CONCAT_0b0_CONCAT_row_count_0_1_PLUS_ETC___d26 =
	     17'd320 * y__h1257 ;
  assign _320_MUL_0_CONCAT_row_count_0_BITS_9_TO_1_8_9___d20 =
	     17'd320 * y__h1177 ;
  assign _theResult_____1__h1512 =
	     (d_prev < 8'd192) ? _theResult_____2__h1511 : result__h1529 ;
  assign _theResult_____1__h2041 =
	     (d_curr < 8'd192) ? _theResult_____2__h2040 : result__h2058 ;
  assign _theResult_____1__h2569 =
	     (data_in < 8'd192) ? _theResult_____2__h2568 : result__h2585 ;
  assign _theResult_____2__h1511 =
	     (d_prev < 8'd160) ? _theResult_____3__h1510 : result__h1539 ;
  assign _theResult_____2__h2040 =
	     (d_curr < 8'd160) ? _theResult_____3__h2039 : result__h2068 ;
  assign _theResult_____2__h2568 =
	     (data_in < 8'd160) ? _theResult_____3__h2567 : result__h2595 ;
  assign _theResult_____3__h1510 =
	     (d_prev < 8'd128) ? _theResult_____4__h1509 : result__h1549 ;
  assign _theResult_____3__h2039 =
	     (d_curr < 8'd128) ? _theResult_____4__h2038 : result__h2078 ;
  assign _theResult_____3__h2567 =
	     (data_in < 8'd128) ? _theResult_____4__h2566 : result__h2605 ;
  assign _theResult_____4__h1509 =
	     (d_prev < 8'd96) ? _theResult_____5__h1508 : result__h1559 ;
  assign _theResult_____4__h2038 =
	     (d_curr < 8'd96) ? _theResult_____5__h2037 : result__h2088 ;
  assign _theResult_____4__h2566 =
	     (data_in < 8'd96) ? _theResult_____5__h2565 : result__h2615 ;
  assign _theResult_____5__h1508 =
	     (d_prev < 8'd64) ? _theResult_____6__h1507 : result__h1569 ;
  assign _theResult_____5__h2037 =
	     (d_curr < 8'd64) ? _theResult_____6__h2036 : result__h2098 ;
  assign _theResult_____5__h2565 =
	     (data_in < 8'd64) ? _theResult_____6__h2564 : result__h2625 ;
  assign _theResult_____6__h1507 = (d_prev < 8'd32) ? 8'd1 : 8'd3 ;
  assign _theResult_____6__h2036 = (d_curr < 8'd32) ? 8'd1 : 8'd3 ;
  assign _theResult_____6__h2564 = (data_in < 8'd32) ? 8'd1 : 8'd3 ;
  assign o_0_0_47_XOR_o_0_2_9___d148 = o_0_0 ^ o_0_2 ;
  assign o_0_0_47_XOR_o_2_0_52___d153 = o_0_0 ^ o_2_0 ;
  assign o_0_1_8_XOR_o_2_1_06___d143 = o_0_1 ^ o_2_1 ;
  assign o_1_0_39_XOR_o_1_2_3___d140 = o_1_0 ^ o_1_2 ;
  assign result__h1519 = { 1'd1, _theResult_____1__h1512[6:0] } ;
  assign result__h1529 =
	     { _theResult_____2__h1511[7],
	       1'd1,
	       _theResult_____2__h1511[5:0] } ;
  assign result__h1539 =
	     { _theResult_____3__h1510[7:6],
	       1'd1,
	       _theResult_____3__h1510[4:0] } ;
  assign result__h1549 =
	     { _theResult_____4__h1509[7:5],
	       1'd1,
	       _theResult_____4__h1509[3:0] } ;
  assign result__h1559 =
	     { _theResult_____5__h1508[7:4],
	       1'd1,
	       _theResult_____5__h1508[2:0] } ;
  assign result__h1569 =
	     { _theResult_____6__h1507[7:3],
	       1'd1,
	       _theResult_____6__h1507[1:0] } ;
  assign result__h2048 = { 1'd1, _theResult_____1__h2041[6:0] } ;
  assign result__h2058 =
	     { _theResult_____2__h2040[7],
	       1'd1,
	       _theResult_____2__h2040[5:0] } ;
  assign result__h2068 =
	     { _theResult_____3__h2039[7:6],
	       1'd1,
	       _theResult_____3__h2039[4:0] } ;
  assign result__h2078 =
	     { _theResult_____4__h2038[7:5],
	       1'd1,
	       _theResult_____4__h2038[3:0] } ;
  assign result__h2088 =
	     { _theResult_____5__h2037[7:4],
	       1'd1,
	       _theResult_____5__h2037[2:0] } ;
  assign result__h2098 =
	     { _theResult_____6__h2036[7:3],
	       1'd1,
	       _theResult_____6__h2036[1:0] } ;
  assign result__h2575 = { 1'd1, _theResult_____1__h2569[6:0] } ;
  assign result__h2585 =
	     { _theResult_____2__h2568[7],
	       1'd1,
	       _theResult_____2__h2568[5:0] } ;
  assign result__h2595 =
	     { _theResult_____3__h2567[7:6],
	       1'd1,
	       _theResult_____3__h2567[4:0] } ;
  assign result__h2605 =
	     { _theResult_____4__h2566[7:5],
	       1'd1,
	       _theResult_____4__h2566[3:0] } ;
  assign result__h2615 =
	     { _theResult_____5__h2565[7:4],
	       1'd1,
	       _theResult_____5__h2565[2:0] } ;
  assign result__h2625 =
	     { _theResult_____6__h2564[7:3],
	       1'd1,
	       _theResult_____6__h2564[1:0] } ;
  assign x__h1043 =
	     x__h1250 +
	     _320_MUL_0_CONCAT_0b0_CONCAT_row_count_0_1_PLUS_ETC___d15[16:0] ;
  assign x__h1098 = { 1'b0, row_count } + 11'd2047 ;
  assign x__h1161 =
	     x__h1250 +
	     _320_MUL_0_CONCAT_row_count_0_BITS_9_TO_1_8_9___d20[16:0] ;
  assign x__h1241 =
	     x__h1250 +
	     _320_MUL_0_CONCAT_0b0_CONCAT_row_count_0_1_PLUS_ETC___d26[16:0] ;
  assign x__h1250 = { 8'd0, col_count[9:1] } ;
  assign x__h1261 = { 1'b0, row_count } + 11'd1 ;
  assign x__h4972 = col_count + 10'd1 ;
  assign y__h1094 = { 8'd0, x__h1098[9:1] } ;
  assign y__h1177 = { 8'd0, row_count[9:1] } ;
  assign y__h1257 = { 8'd0, x__h1261[9:1] } ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        addr_reg <= `BSV_ASSIGNMENT_DELAY 17'd0;
	col_count <= `BSV_ASSIGNMENT_DELAY 10'd4;
	d_curr <= `BSV_ASSIGNMENT_DELAY 8'd0;
	d_prev <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_0_0 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_0_1 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_0_2 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_1_0 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_1_1 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_1_2 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_2_0 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_2_1 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	o_2_2 <= `BSV_ASSIGNMENT_DELAY 8'd0;
	res_reg <= `BSV_ASSIGNMENT_DELAY 8'd0;
	row_count <= `BSV_ASSIGNMENT_DELAY 10'd0;
	state <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (addr_reg$EN) addr_reg <= `BSV_ASSIGNMENT_DELAY addr_reg$D_IN;
	if (col_count$EN) col_count <= `BSV_ASSIGNMENT_DELAY col_count$D_IN;
	if (d_curr$EN) d_curr <= `BSV_ASSIGNMENT_DELAY d_curr$D_IN;
	if (d_prev$EN) d_prev <= `BSV_ASSIGNMENT_DELAY d_prev$D_IN;
	if (o_0_0$EN) o_0_0 <= `BSV_ASSIGNMENT_DELAY o_0_0$D_IN;
	if (o_0_1$EN) o_0_1 <= `BSV_ASSIGNMENT_DELAY o_0_1$D_IN;
	if (o_0_2$EN) o_0_2 <= `BSV_ASSIGNMENT_DELAY o_0_2$D_IN;
	if (o_1_0$EN) o_1_0 <= `BSV_ASSIGNMENT_DELAY o_1_0$D_IN;
	if (o_1_1$EN) o_1_1 <= `BSV_ASSIGNMENT_DELAY o_1_1$D_IN;
	if (o_1_2$EN) o_1_2 <= `BSV_ASSIGNMENT_DELAY o_1_2$D_IN;
	if (o_2_0$EN) o_2_0 <= `BSV_ASSIGNMENT_DELAY o_2_0$D_IN;
	if (o_2_1$EN) o_2_1 <= `BSV_ASSIGNMENT_DELAY o_2_1$D_IN;
	if (o_2_2$EN) o_2_2 <= `BSV_ASSIGNMENT_DELAY o_2_2$D_IN;
	if (res_reg$EN) res_reg <= `BSV_ASSIGNMENT_DELAY res_reg$D_IN;
	if (row_count$EN) row_count <= `BSV_ASSIGNMENT_DELAY row_count$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    addr_reg = 17'h0AAAA;
    col_count = 10'h2AA;
    d_curr = 8'hAA;
    d_prev = 8'hAA;
    o_0_0 = 8'hAA;
    o_0_1 = 8'hAA;
    o_0_2 = 8'hAA;
    o_1_0 = 8'hAA;
    o_1_1 = 8'hAA;
    o_1_2 = 8'hAA;
    o_2_0 = 8'hAA;
    o_2_1 = 8'hAA;
    o_2_2 = 8'hAA;
    res_reg = 8'hAA;
    row_count = 10'h2AA;
    state = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkSobelStoch

