//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:57:15 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// hsync                          O     1
// RDY_hsync                      O     1 const
// vsync                          O     1
// RDY_vsync                      O     1 const
// rgb                            O    12
// RDY_rgb                        O     1 const
// address                        O    17
// RDY_address                    O     1 const
// frame_done                     O     1
// RDY_frame_done                 O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// rgb_data_in                    I     8
//
// Combinational paths from inputs to outputs:
//   rgb_data_in -> rgb
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkVgaDisplay(CLK,
		    RST_N,

		    hsync,
		    RDY_hsync,

		    vsync,
		    RDY_vsync,

		    rgb_data_in,
		    rgb,
		    RDY_rgb,

		    address,
		    RDY_address,

		    frame_done,
		    RDY_frame_done);
  input  CLK;
  input  RST_N;

  // value method hsync
  output hsync;
  output RDY_hsync;

  // value method vsync
  output vsync;
  output RDY_vsync;

  // value method rgb
  input  [7 : 0] rgb_data_in;
  output [11 : 0] rgb;
  output RDY_rgb;

  // value method address
  output [16 : 0] address;
  output RDY_address;

  // value method frame_done
  output frame_done;
  output RDY_frame_done;

  // signals for module outputs
  wire [16 : 0] address;
  wire [11 : 0] rgb;
  wire RDY_address,
       RDY_frame_done,
       RDY_hsync,
       RDY_rgb,
       RDY_vsync,
       frame_done,
       hsync,
       vsync;

  // register h_count
  reg [9 : 0] h_count;
  wire [9 : 0] h_count$D_IN;
  wire h_count$EN;

  // register v_count
  reg [9 : 0] v_count;
  wire [9 : 0] v_count$D_IN;
  wire v_count$EN;

  // remaining internal signals
  wire [33 : 0] _0_CONCAT_v_count_BITS_9_TO_1_0_1_MUL_320___d22;
  wire [16 : 0] h_offset__h310;
  wire [9 : 0] x__h114;

  // value method hsync
  assign hsync = h_count < 10'd688 || h_count > 10'd783 ;
  assign RDY_hsync = 1'd1 ;

  // value method vsync
  assign vsync = v_count < 10'd513 || v_count > 10'd514 ;
  assign RDY_vsync = 1'd1 ;

  // value method rgb
  assign rgb =
	     (h_count < 10'd640 && v_count < 10'd480) ?
	       {3{rgb_data_in[3:0]}} :
	       12'b0 ;
  assign RDY_rgb = 1'd1 ;

  // value method address
  assign address =
	     _0_CONCAT_v_count_BITS_9_TO_1_0_1_MUL_320___d22[16:0] +
	     h_offset__h310 ;
  assign RDY_address = 1'd1 ;

  // value method frame_done
  assign frame_done = v_count == 10'd480 ;
  assign RDY_frame_done = 1'd1 ;

  // register h_count
  assign h_count$D_IN = (h_count == 10'd799) ? 10'd0 : x__h114 ;
  assign h_count$EN = 1'd1 ;

  // register v_count
  assign v_count$D_IN = (v_count == 10'd524) ? 10'd0 : v_count + 10'd1 ;
  assign v_count$EN = h_count == 10'd799 ;

  // remaining internal signals
  assign _0_CONCAT_v_count_BITS_9_TO_1_0_1_MUL_320___d22 =
	     { 8'd0, v_count[9:1] } * 17'd320 ;
  assign h_offset__h310 = { 8'd0, h_count[9:1] } ;
  assign x__h114 = h_count + 10'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        h_count <= `BSV_ASSIGNMENT_DELAY 10'd0;
	v_count <= `BSV_ASSIGNMENT_DELAY 10'd0;
      end
    else
      begin
        if (h_count$EN) h_count <= `BSV_ASSIGNMENT_DELAY h_count$D_IN;
	if (v_count$EN) v_count <= `BSV_ASSIGNMENT_DELAY v_count$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    h_count = 10'h2AA;
    v_count = 10'h2AA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkVgaDisplay

