//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:46:55 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// data_Y                         O     8 reg
// RDY_data_Y                     O     1 const
// address                        O    17 reg
// RDY_address                    O     1 const
// data_valid                     O     1 reg
// RDY_data_valid                 O     1 const
// frame_done                     O     1 reg
// RDY_frame_done                 O     1 const
// CLK_pclk                       I     1 unused
// RST_N_rst                      I     1 unused
// d_in                           I     8 reg
// vsync                          I     1
// hsync                          I     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkCapture(CLK_pclk,
		 RST_N_rst,
		 d_in,
		 vsync,
		 hsync,
		 CLK,
		 RST_N,

		 data_Y,
		 RDY_data_Y,

		 address,
		 RDY_address,

		 data_valid,
		 RDY_data_valid,

		 frame_done,
		 RDY_frame_done);
  input  CLK_pclk;
  input  RST_N_rst;
  input  [7 : 0] d_in;
  input  vsync;
  input  hsync;
  input  CLK;
  input  RST_N;

  // value method data_Y
  output [7 : 0] data_Y;
  output RDY_data_Y;

  // value method address
  output [16 : 0] address;
  output RDY_address;

  // value method data_valid
  output data_valid;
  output RDY_data_valid;

  // value method frame_done
  output frame_done;
  output RDY_frame_done;

  // signals for module outputs
  wire [16 : 0] address;
  wire [7 : 0] data_Y;
  wire RDY_address,
       RDY_data_Y,
       RDY_data_valid,
       RDY_frame_done,
       data_valid,
       frame_done;

  // register addr
  reg [16 : 0] addr;
  wire [16 : 0] addr$D_IN;
  wire addr$EN;

  // register cols
  reg [9 : 0] cols;
  wire [9 : 0] cols$D_IN;
  wire cols$EN;

  // register done
  reg done;
  wire done$D_IN, done$EN;

  // register halfclk
  reg halfclk;
  wire halfclk$D_IN, halfclk$EN;

  // register luma
  reg [7 : 0] luma;
  wire [7 : 0] luma$D_IN;
  wire luma$EN;

  // register rows
  reg [9 : 0] rows;
  wire [9 : 0] rows$D_IN;
  wire rows$EN;

  // register valid
  reg valid;
  wire valid$D_IN, valid$EN;

  // remaining internal signals
  wire [16 : 0] x1_avValue_fst__h483,
		y_avValue_fst__h448,
		y_avValue_fst__h463,
		y_avValue_fst__h480;
  wire [9 : 0] next_rows___1__h523,
	       next_rows__h487,
	       x1_avValue_snd_fst__h611,
	       y_avValue_snd_fst__h507,
	       y_avValue_snd_fst__h608,
	       y_avValue_snd_fst__h615,
	       y_avValue_snd_snd_fst__h601;
  wire NOT_vsync_AND_hsync_AND_halfclk_AND_cols_ULT_3_ETC___d11;

  // value method data_Y
  assign data_Y = luma ;
  assign RDY_data_Y = 1'd1 ;

  // value method address
  assign address = addr ;
  assign RDY_address = 1'd1 ;

  // value method data_valid
  assign data_valid = valid ;
  assign RDY_data_valid = 1'd1 ;

  // value method frame_done
  assign frame_done = done ;
  assign RDY_frame_done = 1'd1 ;

  // register addr
  assign addr$D_IN =
	     (next_rows__h487 == 10'd480) ? 17'h1FFFF : x1_avValue_fst__h483 ;
  assign addr$EN = 1'd1 ;

  // register cols
  assign cols$D_IN = (!vsync && hsync) ? y_avValue_snd_snd_fst__h601 : cols ;
  assign cols$EN = 1'd1 ;

  // register done
  assign done$D_IN = next_rows__h487 == 10'd480 ;
  assign done$EN = 1'd1 ;

  // register halfclk
  assign halfclk$D_IN = ~halfclk ;
  assign halfclk$EN = 1'd1 ;

  // register luma
  assign luma$D_IN = d_in ;
  assign luma$EN = NOT_vsync_AND_hsync_AND_halfclk_AND_cols_ULT_3_ETC___d11 ;

  // register rows
  assign rows$D_IN = (next_rows__h487 == 10'd480) ? 10'd0 : next_rows__h487 ;
  assign rows$EN = 1'd1 ;

  // register valid
  assign valid$D_IN =
	     NOT_vsync_AND_hsync_AND_halfclk_AND_cols_ULT_3_ETC___d11 ;
  assign valid$EN = 1'd1 ;

  // remaining internal signals
  assign NOT_vsync_AND_hsync_AND_halfclk_AND_cols_ULT_3_ETC___d11 =
	     !vsync && hsync && halfclk && cols < 10'd320 && rows < 10'd240 ;
  assign next_rows___1__h523 = rows + 10'd1 ;
  assign next_rows__h487 =
	     (!vsync && hsync) ? y_avValue_snd_fst__h507 : rows ;
  assign x1_avValue_fst__h483 =
	     (!vsync && hsync) ? y_avValue_fst__h480 : addr ;
  assign x1_avValue_snd_fst__h611 = halfclk ? y_avValue_snd_fst__h608 : cols ;
  assign y_avValue_fst__h448 = addr + 17'd1 ;
  assign y_avValue_fst__h463 =
	     (cols < 10'd320 && rows < 10'd240) ? y_avValue_fst__h448 : addr ;
  assign y_avValue_fst__h480 = halfclk ? y_avValue_fst__h463 : addr ;
  assign y_avValue_snd_fst__h507 =
	     (cols == 10'd639 && !halfclk) ? next_rows___1__h523 : rows ;
  assign y_avValue_snd_fst__h608 =
	     (cols < 10'd639) ? y_avValue_snd_fst__h615 : cols ;
  assign y_avValue_snd_fst__h615 = cols + 10'd1 ;
  assign y_avValue_snd_snd_fst__h601 =
	     (cols == 10'd639 && !halfclk) ?
	       10'd0 :
	       x1_avValue_snd_fst__h611 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        addr <= `BSV_ASSIGNMENT_DELAY 17'h1FFFF;
	cols <= `BSV_ASSIGNMENT_DELAY 10'd0;
	done <= `BSV_ASSIGNMENT_DELAY 1'd0;
	halfclk <= `BSV_ASSIGNMENT_DELAY 1'd1;
	luma <= `BSV_ASSIGNMENT_DELAY 8'd0;
	rows <= `BSV_ASSIGNMENT_DELAY 10'd0;
	valid <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (addr$EN) addr <= `BSV_ASSIGNMENT_DELAY addr$D_IN;
	if (cols$EN) cols <= `BSV_ASSIGNMENT_DELAY cols$D_IN;
	if (done$EN) done <= `BSV_ASSIGNMENT_DELAY done$D_IN;
	if (halfclk$EN) halfclk <= `BSV_ASSIGNMENT_DELAY halfclk$D_IN;
	if (luma$EN) luma <= `BSV_ASSIGNMENT_DELAY luma$D_IN;
	if (rows$EN) rows <= `BSV_ASSIGNMENT_DELAY rows$D_IN;
	if (valid$EN) valid <= `BSV_ASSIGNMENT_DELAY valid$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    addr = 17'h0AAAA;
    cols = 10'h2AA;
    done = 1'h0;
    halfclk = 1'h0;
    luma = 8'hAA;
    rows = 10'h2AA;
    valid = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkCapture

