//
// Generated by Bluespec Compiler, version 2026.01 (build 9bd39e6f)
//
// On Sat May  2 01:49:39 IST 2026
//
//
// Ports:
// Name                         I/O  size props
// write_en                       O     1
// RDY_write_en                   O     1 const
// read_en                        O     1
// RDY_read_en                    O     1 const
// select                         O     1 reg
// RDY_select                     O     1 const
// state_info                     O     3 reg
// RDY_state_info                 O     1 const
// en                             I     1
// writing_done                   I     1
// display_done                   I     1
// video_on                       I     1
// data_valid                     I     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// Combinational paths from inputs to outputs:
//   video_on -> read_en
//   data_valid -> write_en
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkReadWriteController(en,
			     writing_done,
			     display_done,
			     video_on,
			     data_valid,
			     CLK,
			     RST_N,

			     write_en,
			     RDY_write_en,

			     read_en,
			     RDY_read_en,

			     select,
			     RDY_select,

			     state_info,
			     RDY_state_info);
  input  en;
  input  writing_done;
  input  display_done;
  input  video_on;
  input  data_valid;
  input  CLK;
  input  RST_N;

  // value method write_en
  output write_en;
  output RDY_write_en;

  // value method read_en
  output read_en;
  output RDY_read_en;

  // value method select
  output select;
  output RDY_select;

  // value method state_info
  output [2 : 0] state_info;
  output RDY_state_info;

  // signals for module outputs
  wire [2 : 0] state_info;
  wire RDY_read_en,
       RDY_select,
       RDY_state_info,
       RDY_write_en,
       read_en,
       select,
       write_en;

  // register r_en
  reg r_en;
  wire r_en$D_IN, r_en$EN;

  // register sel
  reg sel;
  wire sel$D_IN, sel$EN;

  // register state
  reg [2 : 0] state;
  reg [2 : 0] state$D_IN;
  wire state$EN;

  // register w_en
  reg w_en;
  wire w_en$D_IN, w_en$EN;

  // remaining internal signals
  wire state_EQ_0_AND_en_OR_NOT_state_EQ_0_AND_state__ETC___d21;

  // value method write_en
  assign write_en = w_en && data_valid ;
  assign RDY_write_en = 1'd1 ;

  // value method read_en
  assign read_en = r_en && video_on ;
  assign RDY_read_en = 1'd1 ;

  // value method select
  assign select = sel ;
  assign RDY_select = 1'd1 ;

  // value method state_info
  assign state_info = state ;
  assign RDY_state_info = 1'd1 ;

  // register r_en
  assign r_en$D_IN = state == 3'd2 ;
  assign r_en$EN = (state == 3'd2 || state == 3'd3) && display_done ;

  // register sel
  assign sel$D_IN = state == 3'd2 ;
  assign sel$EN = (state == 3'd2 || state == 3'd3) && display_done ;

  // register state
  always@(state)
  begin
    case (state)
      3'd0, 3'd3: state$D_IN = 3'd4;
      3'd1: state$D_IN = 3'd2;
      3'd2: state$D_IN = 3'd3;
      default: state$D_IN = 3'd1;
    endcase
  end
  assign state$EN = state_EQ_0_AND_en_OR_NOT_state_EQ_0_AND_state__ETC___d21 ;

  // register w_en
  assign w_en$D_IN = state != 3'd1 ;
  assign w_en$EN = (state == 3'd1 || state == 3'd4) && writing_done ;

  // remaining internal signals
  assign state_EQ_0_AND_en_OR_NOT_state_EQ_0_AND_state__ETC___d21 =
	     state == 3'd0 && en ||
	     state != 3'd0 &&
	     (state == 3'd1 && writing_done ||
	      state != 3'd1 &&
	      (state == 3'd2 && display_done ||
	       state == 3'd3 && display_done ||
	       state == 3'd4 && writing_done)) ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        r_en <= `BSV_ASSIGNMENT_DELAY 1'd0;
	sel <= `BSV_ASSIGNMENT_DELAY 1'd0;
	state <= `BSV_ASSIGNMENT_DELAY 3'd0;
	w_en <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (r_en$EN) r_en <= `BSV_ASSIGNMENT_DELAY r_en$D_IN;
	if (sel$EN) sel <= `BSV_ASSIGNMENT_DELAY sel$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
	if (w_en$EN) w_en <= `BSV_ASSIGNMENT_DELAY w_en$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    r_en = 1'h0;
    sel = 1'h0;
    state = 3'h2;
    w_en = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkReadWriteController

